# -*- encoding: utf-8 -*-

require 'rumoji/emoji'
require 'set'

module Rumoji
  class Emoji
    OBJECTS = Set[
      self.new("1F38D", [:bamboo], "PINE DECORATION"), # "Japanese new year's door decoration
      self.new("1F49D", [:gift_heart], "HEART WITH RIBBON"),
      self.new("1F38E", [:dolls], "JAPANESE DOLLS"), # "Japanese Hinamatsuri or girls' doll festival"
      self.new("1F49D", [:gift_heart], "HEART WITH RIBBON"),
      self.new("1F392", [:school_satchel]), # "Japanese school entrance ceremony"
      self.new("1F393", [:mortar_board], "GRADUATION CAP"), # "graduation ceremony"
      self.new("1F38F", [:flags], "CARP STREAMER"),
      self.new("1F386", [:fireworks]),
      self.new("1F387", [:sparkler], "FIREWORK SPARKLER"),
      self.new("1F390", [:wind_chime]),
      self.new("1F391", [:rice_scene], "MOON VIEWING CEREMONY"), # "Japanese Otsukimi harvest celebration"
      self.new("1F383", [:jack_o_lantern], "JACK-O-LANTERN"), # "Hallowe'en"
      self.new("1F47B", [:ghost]),
      self.new("1F385", [:santa], "FATHER CHRISTMAS"), # "Santa Claus"
      self.new("1f3b1", [:"8ball"]),
      self.new("23f0" , [:alarm_clock]),
      self.new("1f34e", [:apple]),
      self.new("1f3a8", [:art]),
      self.new("1f37c", [:baby_bottle]),
      self.new("1f388", [:balloon]),
      self.new("1f34c", [:banana]),
      self.new("1f4ca", [:bar_chart]),
      self.new("26be" , [:baseball]),
      self.new("1f3c0", [:basketball]),
      self.new("1f6c0", [:bath]),
      self.new("1f6c1", [:bathtub]),
      self.new("1f50b", [:battery]),
      self.new("1f37a", [:beer]),
      self.new("1f37b", [:beers]),
      self.new("1f514", [:bell]),
      self.new("1f371", [:bento]),
      self.new("1f6b4", [:bicyclist]),
      self.new("1f459", [:bikini]),
      self.new("1f382", [:birthday]),
      self.new("1f0cf", [:black_joker]),
      self.new("2712" , [:black_nib]),
      self.new("1f4d8", [:blue_book]),
      self.new("1f4a3", [:bomb]),
      self.new("1f516", [:bookmark]),
      self.new("1f4d1", [:bookmark_tabs]),
      self.new("1f4da", [:books]),
      self.new("1f462", [:boot]),
      self.new("1f3b3", [:bowling]),
      self.new("1f35e", [:bread]),
      self.new("1f4bc", [:briefcase]),
      self.new("1f4a1", [:bulb]),
      self.new("1f370", [:cake]),
      self.new("1f4c6", [:calendar]),
      self.new("1f4f2", [:calling]),
      self.new("1f4f7", [:camera]),
      self.new("1f36c", [:candy]),
      self.new("1f4c7", [:card_index]),
      self.new("1f4bf", [:cd]),
      self.new("1f4c9", [:chart_with_downwards_trend]),
      self.new("1f4c8", [:chart_with_upwards_trend]),
      self.new("1f352", [:cherries]),
      self.new("1f36b", [:chocolate_bar]),
      self.new("1f384", [:christmas_tree]),
      self.new("1f3ac", [:clapper]),
      self.new("1f4cb", [:clipboard]),
      self.new("1f4d5", [:closed_book]),
      self.new("1f510", [:closed_lock_with_key]),
      self.new("1f302", [:closed_umbrella]),
      self.new("2663" , [:clubs]),
      self.new("1f378", [:cocktail]),
      self.new("2615" , [:coffee]),
      self.new("1f4bb", [:computer]),
      self.new("1f38a", [:confetti_ball]),
      self.new("1f36a", [:cookie]),
      self.new("1f33d", [:corn]),
      self.new("1f4b3", [:credit_card]),
      self.new("1f451", [:crown]),
      self.new("1f52e", [:crystal_ball]),
      self.new("1f35b", [:curry]),
      self.new("1f36e", [:custard]),
      self.new("1f361", [:dango]),
      self.new("1f3af", [:dart]),
      self.new("1f4c5", [:date]),
      self.new("2666" , [:diamonds]),
      self.new("1f4b5", [:dollar]),
      self.new("1f6aa", [:door]),
      self.new("1f369", [:doughnut]),
      self.new("1f457", [:dress]),
      self.new("1f4c0", [:dvd]),
      self.new("1f4e7", [:"e-mail"]),
      self.new("1f373", [:egg]),
      self.new("1f346", [:eggplant]),
      self.new("1f50c", [:electric_plug]),
      self.new("2709" , [:email, :envelope]),
      self.new("1f4b6", [:euro]),
      self.new("1f453", [:eyeglasses]),
      self.new("1f4e0", [:fax]),
      self.new("1f4c1", [:file_folder]),
      self.new("1f365", [:fish_cake]),
      self.new("1f3a3", [:fishing_pole_and_fish]),
      self.new("1f526", [:flashlight]),
      self.new("1f4be", [:floppy_disk]),
      self.new("1f3b4", [:flower_playing_cards]),
      self.new("1f3c8", [:football]),
      self.new("1f374", [:fork_and_knife]),
      self.new("1f364", [:fried_shrimp]),
      self.new("1f35f", [:fries]),
      self.new("1f3b2", [:game_die]),
      self.new("1f48e", [:gem]),
      self.new("1f381", [:gift]),
      self.new("26f3" , [:golf]),
      self.new("1f347", [:grapes]),
      self.new("1f34f", [:green_apple]),
      self.new("1f4d7", [:green_book]),
      self.new("1f3b8", [:guitar]),
      self.new("1f52b", [:gun]),
      self.new("1f354", [:hamburger]),
      self.new("1f528", [:hammer]),
      self.new("1f45c", [:handbag]),
      self.new("1f3a7", [:headphones]),
      self.new("2665" , [:hearts]),
      self.new("1f506", [:high_brightness]),
      self.new("1f460", [:high_heel]),
      self.new("1f52a", [:hocho]),
      self.new("1f36f", [:honey_pot]),
      self.new("1f3c7", [:horse_racing]),
      self.new("231b" , [:hourglass]),
      self.new("23f3" , [:hourglass_flowing_sand]),
      self.new("1f368", [:ice_cream]),
      self.new("1f366", [:icecream]),
      self.new("1f4e5", [:inbox_tray]),
      self.new("1f4e8", [:incoming_envelope]),
      self.new("1f4f1", [:iphone]),
      self.new("1f456", [:jeans]),
      self.new("1f511", [:key]),
      self.new("1f458", [:kimono]),
      self.new("1f4d2", [:ledger]),
      self.new("1f34b", [:lemon]),
      self.new("1f484", [:lipstick]),
      self.new("1f512", [:lock]),
      self.new("1f50f", [:lock_with_ink_pen]),
      self.new("1f36d", [:lollipop]),
      self.new("27bf" , [:loop]),
      self.new("1f4e2", [:loudspeaker]),
      self.new("1f505", [:low_brightness]),
      self.new("1f50d", [:mag]),
      self.new("1f50e", [:mag_right]),
      self.new("1f004", [:mahjong]),
      self.new("1f4eb", [:mailbox]),
      self.new("1f4ea", [:mailbox_closed]),
      self.new("1f4ec", [:mailbox_with_mail]),
      self.new("1f4ed", [:mailbox_with_no_mail]),
      self.new("1f45e", [:mans_shoe, :shoe]),
      self.new("1f356", [:meat_on_bone]),
      self.new("1f4e3", [:mega]),
      self.new("1f348", [:melon]),
      self.new("1f4dd", [:memo, :pencil]),
      self.new("1f3a4", [:microphone]),
      self.new("1f52c", [:microscope]),
      self.new("1f4bd", [:minidisc]),
      self.new("1f4b8", [:money_with_wings]),
      self.new("1f4b0", [:moneybag]),
      self.new("1f6b5", [:mountain_bicyclist]),
      self.new("1f3a5", [:movie_camera]),
      self.new("1f3b9", [:musical_keyboard]),
      self.new("1f3bc", [:musical_score]),
      self.new("1f507", [:mute]),
      self.new("1f4db", [:name_badge]),
      self.new("1f454", [:necktie]),
      self.new("1f4f0", [:newspaper]),
      self.new("1f515", [:no_bell]),
      self.new("1f4d3", [:notebook]),
      self.new("1f4d4", [:notebook_with_decorative_cover]),
      self.new("1f529", [:nut_and_bolt]),
      self.new("1f362", [:oden]),
      self.new("1f4c2", [:open_file_folder]),
      self.new("1f4d9", [:orange_book]),
      self.new("1f4e4", [:outbox_tray]),
      self.new("1f4c4", [:page_facing_up]),
      self.new("1f4c3", [:page_with_curl]),
      self.new("1f4df", [:pager]),
      self.new("1f4ce", [:paperclip]),
      self.new("1f351", [:peach]),
      self.new("1f350", [:pear]),
      self.new("270f" , [:pencil2]),
      self.new("260e" , [:phone, :telephone]),
      self.new("1f48a", [:pill]),
      self.new("1f34d", [:pineapple]),
      self.new("1f355", [:pizza]),
      self.new("1f4ef", [:postal_horn]),
      self.new("1f4ee", [:postbox]),
      self.new("1f45d", [:pouch]),
      self.new("1f357", [:poultry_leg]),
      self.new("1f4b7", [:pound]),
      self.new("1f45b", [:purse]),
      self.new("1f4cc", [:pushpin]),
      self.new("1f4fb", [:radio]),
      self.new("1f35c", [:ramen]),
      self.new("1f380", [:ribbon]),
      self.new("1f35a", [:rice]),
      self.new("1f359", [:rice_ball]),
      self.new("1f358", [:rice_cracker]),
      self.new("1f48d", [:ring]),
      self.new("1f3c9", [:rugby_football]),
      self.new("1f3bd", [:running_shirt_with_sash]),
      self.new("1f376", [:sake]),
      self.new("1f461", [:sandal]),
      self.new("1f4e1", [:satellite]),
      self.new("1f3b7", [:saxophone]),
      self.new("2702" , [:scissors]),
      self.new("1f4dc", [:scroll]),
      self.new("1f4ba", [:seat]),
      self.new("1f367", [:shaved_ice]),
      self.new("1f455", [:shirt, :tshirt]),
      self.new("1f6bf", [:shower]),
      self.new("1f3bf", [:ski]),
      self.new("1f6ac", [:smoking]),
      self.new("1f3c2", [:snowboarder]),
      self.new("26bd" , [:soccer]),
      self.new("1f509", [:sound]),
      self.new("1f47e", [:space_invader]),
      self.new("2660" , [:spades]),
      self.new("1f35d", [:spaghetti]),
      self.new("1f50a", [:speaker]),
      self.new("1f372", [:stew]),
      self.new("1f4cf", [:straight_ruler]),
      self.new("1f353", [:strawberry]),
      self.new("1f3c4", [:surfer]),
      self.new("1f363", [:sushi]),
      self.new("1f360", [:sweet_potato]),
      self.new("1f3ca", [:swimmer]),
      self.new("1f489", [:syringe]),
      self.new("1f389", [:tada]),
      self.new("1f38b", [:tanabata_tree]),
      self.new("1f34a", [:tangerine]),
      self.new("1f375", [:tea]),
      self.new("1f4de", [:telephone_receiver]),
      self.new("1f52d", [:telescope]),
      self.new("1f3be", [:tennis]),
      self.new("1f6bd", [:toilet]),
      self.new("1f345", [:tomato]),
      self.new("1f3a9", [:tophat]),
      self.new("1f4d0", [:triangular_ruler]),
      self.new("1f3c6", [:trophy]),
      self.new("1f379", [:tropical_drink]),
      self.new("1f3ba", [:trumpet]),
      self.new("1f4fa", [:tv]),
      self.new("1f513", [:unlock]),
      self.new("1f4fc", [:vhs]),
      self.new("1f4f9", [:video_camera]),
      self.new("1f3ae", [:video_game]),
      self.new("1f3bb", [:violin]),
      self.new("231a" , [:watch]),
      self.new("1f349", [:watermelon]),
      self.new("1f377", [:wine_glass]),
      self.new("1f45a", [:womans_clothes]),
      self.new("1f452", [:womans_hat]),
      self.new("1f527", [:wrench]),
      self.new("1f4b4", [:yen])
    ]
  end
end
